// app/layout.test.tsx
import { render, screen } from "@testing-library/react";
import React from "react";
import RootLayout, { metadata } from "./layout";
import { describe, it, expect, vi } from "vitest";

vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "geist-sans" }),
  Geist_Mono: () => ({ variable: "geist-mono" }),
}));

/* vi.mock("next/image", () => ({
  __esModule: true,
  default: (props: React.ImgHTMLAttributes<HTMLImageElement>) => <img {...props} />,
})); */

vi.mock("./storeProvider", () => ({
  __esModule: true,
  default: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

describe("RootLayout", () => {
  it("exporta el metadata correcto", () => {
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });

  it("renderiza lang en <html>, clases en <body> y el logo", () => {
    render(
      <RootLayout>
        <div data-testid="contenido">Hola</div>
      </RootLayout>
    );

    const htmlEl = document.documentElement;
    expect(htmlEl).toBeTruthy();
    expect(htmlEl.getAttribute("lang")).toBe("en");

    const bodyEl = document.body;
    expect(bodyEl).toBeTruthy();
    expect(bodyEl.className).toContain("geist-sans");
    expect(bodyEl.className).toContain("geist-mono");
    expect(bodyEl.classList.contains("background")).toBe(true);

    const logo = screen.getByRole("img", { name: /logo/i });
    expect(logo).toBeInTheDocument();
    expect(logo).toHaveAttribute("src", "/logo.png");
    expect(logo).toHaveAttribute("width", "332");
    expect(logo).toHaveAttribute("height", "95");

    expect(screen.getByTestId("contenido")).toHaveTextContent("Hola");
  });
});